version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - innofyre-bridge

networks:
  innofyre-bridge:
    name: innofyre-bridge
