version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - innofyre-bridge
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      database:
        condition: service_healthy # Wait for the database service to be healthy

  database:
    container_name: chefs_database
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - innofyre-bridge
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-h",
          "localhost",
          "-p",
          "5432",
          "-d",
          "postgres",
        ]
      interval: 5s
      retries: 5
volumes:
  pgdata: {}

networks:
  innofyre-bridge:
    name: innofyre-bridge
