# Use the official PostgreSQL image as the base image
FROM postgres:12

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Expose the PostgreSQL port
EXPOSE 5432

# Specify the volume for data persistence
VOLUME /var/lib/postgresql/data
