name: Deploy to Gitpod

on:
  push:
    branches:
      - main

env:
  MAVEN_CLI_OPTS: -Dmaven.repo.local=./.m2/repository --batch-mode

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR (GITHUB CONTAINER REGISTRY)
        run: |
          echo ${{ secrets.GHCR_PWD }} | docker login https://ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - run: |
          mkdir -p .m2/repository
          du -h -d1 .m2/repository
          mvn $MAVEN_CLI_OPTS compile jib:build -Djib.to.image=ghcr.io/sukalpomitra/bcgov-code-challenge:latest

      - name: push Docker image
        run: docker push ghcr.io/sukalpomitra/bcgov-code-challenge:latest
