name: Deploy Images to GHCR

# Trigger the workflow on a push event to specific branch
on:
  push:
    branches:
      - main
      - development

# Define jobs for building and pushing Docker images
jobs:
  # Job to build and push the frontend Docker image
  build-push-frontend:
    # needs:
    #   - run-cypress-tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repository
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      # Log in to the GitHub Container Registry using Docker login-action
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
           # the username and password are hardcoded only for demo purposes
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PWD }}

      # Build and push the Docker image for the frontend
      - name: "Build and push Docker image frontend"
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/arshad-innofyre/bcgov-code-challenge-frontend:latest

  # Job to build and push the backend Docker image
  build-push-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repository
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      # Log in to the GitHub Container Registry using Docker login-action
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # the username and password are hardcoded only for demo purposes
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PWD }}

      # Build and push the Docker image for the backend
      - name: "Build and push Docker image backend"
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/sukalpomitra/bcgov-code-challenge-backend:latest

  # Job to build and push the database Docker image
  build-push-database:
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repository
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      # Log in to the GitHub Container Registry using Docker login-action
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # the username and password are hardcoded only for demo purposes
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PWD }}

      # Build and push the Docker image for the database
      - name: "Build and push Docker image database"
        uses: docker/build-push-action@v2
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: ghcr.io/sukalpomitra/bcgov-code-challenge-database:latest

  # Job to run Cypress tests in the frontend
  # run-cypress-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout the GitHub repository
  #     - name: "Checkout GitHub Action"
  #       uses: actions/checkout@main

  #     # Install dependencies and run Cypress tests
  #     - name: "Run Cypress tests"
  #       run: |
  #         cd frontend
  #         npm install
  #         npx cypress run
